package com.example.easymart.presentation.ui.admin.products.add_edit

data class AdminAddEditProductUiState(
    val productId: Int? = null,
    val isEdit: Boolean = false,
    val createdAt: Long = 0L,
    val ratingRate: Double = 0.0,
    val ratingCount: Int = 0,
    val isVisible: Boolean = true,
    val storagePath: String? = null,
    val title: String = "",
    val price: String = "",
    val description: String = "",
    val category: String = "",
    val categories: List<String> = emptyList(),
    val quantity: String = "",
    val mainImageUri: String = "",
    val imageUris: List<String> = emptyList(),
    val selectedImageIndex: Int = 0,
    val scanImageIndex: Int? = null,
    val scanImageUri: String? = null,
    val isLoading: Boolean = false,
    val error: String? = null,
    val titleError: String? = null,
    val priceError: String? = null,
    val descriptionError: String? = null,
    val categoryError: String? = null,
    val quantityError: String? = null,
    val imageUriError: String? = null,
    val isScanning: Boolean = false,
    val ocrText: String = "",
    val scanError: String? = null,
    val scanSuccess: Boolean = false,
    val suggestedTitle: String? = null,
    val suggestedCategory: String? = null,
    val suggestedDescription: String? = null,
    val suggestionConfidence: Float? = null,
    val aiFilledTitle: Boolean = false,
    val aiFilledCategory: Boolean = false,
    val aiFilledDescription: Boolean = false
)
